version: "2"
services:
  app:
    container_name: afs
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sggstrpw
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
